USE STAGING_BNDES_DB;
GO
CREATE TABLE [ST_EMP_BNDES](
    [NOME] VARCHAR(100) NOT NULL,
    [CARGO] VARCHAR(100) NOT NULL,
    [FUNC_OP] VARCHAR(100) NOT NULL,
    [LOT_COMPL] VARCHAR(100) NOT NULL,
    [DESC_UNID_ORG] VARCHAR(100) NOT NULL,
    [LOCAL] VARCHAR(100) NOT NULL,
    [DT_ADM] DATE NOT NULL
);
GO